spring:
  application:
    name: city-api-service
  datasource:
    url: jdbc:postgresql://localhost:5433/citydb
    username: postgres
    password: postgres
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.xml
    drop-first: false
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
server:
  port: 8080
management:
  endpoints:
    web:
      cors:
        allowed-headers: "*"
        allowed-origins: "*"
        allowed-methods: "OPTIONS,GET,POST"
